In [1]:
import numpy as np

#### 1. Write code to create a 4x3 matrix with values ranging from 2 to 13.

In [2]:
arr1 = np.arange(2,14).reshape(4,3)


In [3]:
arr1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

#### 2. Write code to replace the odd numbers by -1 in the array created by using random.randint( 1 , 50,20)

In [4]:
arr1 = np.random.randint(1,50,20)
arr1[arr1 % 2 != 0] = -1
arr1

array([-1, -1, -1,  8, -1, 38, 48, -1, -1, -1,  4, -1, -1, -1, -1, -1, -1,
       -1, -1, 38], dtype=int32)

### 3. Perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999.
##### a. Create a 1d-array of mobile phones prices



In [5]:
arr = np.array([6999,7500,11999,27899,14999,9999])
arr

array([ 6999,  7500, 11999, 27899, 14999,  9999])

##### b. Convert this array to float type

In [6]:
arr = arr.astype(float)
arr

array([ 6999.,  7500., 11999., 27899., 14999.,  9999.])

##### c. Append a new mobile having price of 13999 Rs. to this array

In [7]:
arr = np.append(arr,13999)
arr

array([ 6999.,  7500., 11999., 27899., 14999.,  9999., 13999.])

##### d. Reverse this array of mobile phones prices

In [8]:
arr = arr[::-1]
arr

array([13999.,  9999., 14999., 27899., 11999.,  7500.,  6999.])

##### e. Apply GST of 18% on mobile phones prices and update this array.

In [9]:
price = np.array([6999,7500,11999,27899,14999,9999,13999])
price

array([ 6999,  7500, 11999, 27899, 14999,  9999, 13999])

In [10]:
price = price * 1.18
price

array([ 8258.82,  8850.  , 14158.82, 32920.82, 17698.82, 11798.82,
       16518.82])

##### f. Sort the array in descending order of price

In [11]:
price = np.sort(price)
price[::-1]

array([32920.82, 17698.82, 16518.82, 14158.82, 11798.82,  8850.  ,
        8258.82])

##### g. What is the average mobile phone price

In [12]:
price = np.mean(price)
price

np.float64(15743.560000000001)

##### h. What is the difference b/w maximum and minimum price

In [13]:
price = np.array([32920.82,17698.82,16518.82,14158.82,11798.82,8850.,8258.82])
diff = np.max(price) - np.min(price)
diff

np.float64(24662.0)

### 4. Find out the indices of non zero element in given array [1,2,0,0,4,0]

In [14]:
arr = np.array([1,2,0,0,4,0])
arr

array([1, 2, 0, 0, 4, 0])

In [15]:
indices = np.nonzero(arr)
indices

(array([0, 1, 4]),)

In [18]:
p = np.arange([0,1])
p

TypeError: unsupported operand type(s) for -: 'list' and 'int'