## 2. Assignment on Numpy

### 1. Create a NumPy array containing integers from 0 to 9.

In [1]:
import numpy as np

In [5]:
arr = np.arange(0,9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### 2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50].

In [8]:
mylist = [10,20,30,40]
pyarr = np.array(mylist)
pyarr

array([10, 20, 30, 40])

### 3. Create a 2D array (3x3) with values ranging from 0 to 8.

In [12]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 4. Given a 2D array, find its shape and size. Create a 5x4 array with random integers between 1 and 100, and print the shape and size.

In [14]:
arr.shape

(3, 3)

In [15]:
arr.size

9

In [24]:
arr1 = np.random.randint(1,100 ,size = (5,4))
arr1

array([[27, 93, 66, 74],
       [19, 56, 35, 50],
       [72, 53,  5, 18],
       [48, 15, 44, 56],
       [93, 74,  4, 64]], dtype=int32)

In [25]:
arr1.shape

(5, 4)

In [26]:
arr1.size

20

### 5. Create a 3x3 array of integers and access:

In [27]:
arr = np.random.randint(1,30,size = (3,3))
arr

array([[25, 17, 21],
       [22, 17, 28],
       [22, 16, 25]], dtype=int32)

#### a.The second element of the first row.


In [29]:
second = arr[0,1]
second

np.int32(17)

#### b. The third column of the 2nd row.

In [32]:
ele = arr[1,2]
ele

np.int32(28)

#### c. A subarray with the first two rows and last two columns.

In [45]:

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
arr

subarray = arr[0:2, 1:3]
subarray

array([[20, 30],
       [50, 60]])

### 6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [49]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 7. Reshape a 3x3 matrix into a 1D array.

In [52]:
arr3D = np.random.randint(1,29,size = (3,3))
arr3D

array([[18, 19,  6],
       [ 8, 23, 14],
       [28,  2, 20]], dtype=int32)

In [57]:
oneD = arr3D.reshape(9)
oneD

array([18, 19,  6,  8, 23, 14, 28,  2, 20], dtype=int32)

### 8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition,subtraction, multiplication, and division on them.

In [58]:
arr1 = np.random.randint(1,30,size = (2,3))
arr1

array([[19,  4,  2],
       [26, 25, 25]], dtype=int32)

In [59]:
arr2 = np.random.randint(30,50,size = (2,3))
arr2

array([[39, 44, 45],
       [34, 38, 42]], dtype=int32)

In [60]:
addition = arr1 + arr2
addition

array([[58, 48, 47],
       [60, 63, 67]], dtype=int32)

In [62]:
sub = arr2 - arr1
sub

array([[20, 40, 43],
       [ 8, 13, 17]], dtype=int32)

In [63]:
multi = arr1 * arr2
multi

array([[ 741,  176,   90],
       [ 884,  950, 1050]], dtype=int32)

In [65]:
division = arr2 // arr1
division

array([[ 2, 11, 22],
       [ 1,  1,  1]], dtype=int32)

### 9. Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a given array.

In [66]:
arr = np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [68]:
sum_value = np.sum(arr)
sum_value

np.int64(100)

In [69]:
avg = np.mean(arr)
avg

np.float64(25.0)

In [70]:
standard_d = np.std(arr)
standard_d

np.float64(11.180339887498949)

### 10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @ operator.