## multidimentional Array

In [3]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr1.ndim

2

In [5]:
arr1.shape

(2, 4)

In [7]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr1 = ([[1,2,3],
         [4,5,6],
         [7,8,9]])
arr1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
arr1 = np.array([[[1,2],
                  [3,4]],

                  [[5,6],
                   [7,8]]])
arr1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
arr2 = np.array([[[10,20,30],
                  [45,67,89],
                  [20,30,70]],

                 [[11,22,33],
                  [44,55,66],
                  [77,88,99]]])
arr2

array([[[10, 20, 30],
        [45, 67, 89],
        [20, 30, 70]],

       [[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]]])

## Broadcasting

In [6]:
arr1 = np.array([[10,20,30,40],
                 [50,60,70,80]])
arr2 = np.array([1,2,3,4])

In [7]:
arr3 = arr1 + arr2
arr3

array([[11, 22, 33, 44],
       [51, 62, 73, 84]])

In [4]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1,2,3])
arr3 = arr1+arr2
arr3

ValueError: operands could not be broadcast together with shapes (7,) (3,) 

In [15]:
arr2 = np.pad(arr2,(0,4))

In [16]:
arr2

array([1, 2, 3, 0, 0, 0, 0])

In [17]:
arr3 = arr1 + arr2

In [18]:
arr3

array([2, 4, 6, 4, 5, 6, 7])

## Different ways to create arrays in NumPy

In [19]:
list1 = [18,45,67]
arr1 = np.array(list1)

In [20]:
arr1

array([18, 45, 67])

In [21]:
t1 = (1,2,3)
arr1 = np.array(t1)

In [22]:
arr1

array([1, 2, 3])

In [23]:
dic = {1,2,3}
arr1 = np.array(dic)

In [24]:
arr1

array({1, 2, 3}, dtype=object)

In [26]:
s1 = {1,2,3}
arr1 = np.array(s1)
arr1

array({1, 2, 3}, dtype=object)

In [27]:
arr1.size

1

In [28]:
arr1 = np.arange(1,11)

In [29]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr1 = np.arange(1,50,5)
arr1

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [32]:
arr1 = np.random.randint(1,50,5)
arr1

array([ 7, 49, 10, 26, 14], dtype=int32)

In [35]:
arr1 = np.linspace(1,10,25) # linearly separated no.s in given

In [36]:
arr1

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [37]:
arr1 = np.zeros(5)

In [38]:
arr1

array([0., 0., 0., 0., 0.])

In [39]:
arr1 = np.ones(5)
arr1

array([1., 1., 1., 1., 1.])

In [40]:
arr1 = np.eye(4)
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

In [9]:
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [11]:
arr.itemsize

8

# Functions

In [3]:
arr1 = np.random.randint(1,50,25)
arr1

array([27,  3, 33, 24, 23, 15, 24, 27, 24, 45, 46, 32, 42,  9,  9, 31, 19,
        9, 22, 12, 34, 32, 30, 14, 21], dtype=int32)

In [5]:
arr1 = arr1.reshape(5,5)
arr1

array([[27,  3, 33, 24, 23],
       [15, 24, 27, 24, 45],
       [46, 32, 42,  9,  9],
       [31, 19,  9, 22, 12],
       [34, 32, 30, 14, 21]], dtype=int32)

In [6]:
arr2 = np.random.randint(1,100,10)
arr2

array([60, 14, 26, 12, 13, 64, 83,  6, 87, 26], dtype=int32)

In [7]:
arr2.min()

np.int32(6)

In [8]:
arr2.max()

np.int32(87)

In [9]:
arr2.mean()

np.float64(39.1)

In [10]:
arr2.sum()

np.int64(391)

In [11]:
arr2.argmax()

np.int64(8)

In [12]:
arr1

array([[27,  3, 33, 24, 23],
       [15, 24, 27, 24, 45],
       [46, 32, 42,  9,  9],
       [31, 19,  9, 22, 12],
       [34, 32, 30, 14, 21]], dtype=int32)

In [13]:
arr1.min(axis = 0)
##axis = 0 column
## AXIS = 1 row

array([15,  3,  9,  9,  9], dtype=int32)

## Selection

In [14]:
arr2

array([60, 14, 26, 12, 13, 64, 83,  6, 87, 26], dtype=int32)

In [16]:
arr2[5]

np.int32(64)

In [17]:
arr2[0:2]

array([60, 14], dtype=int32)

In [18]:
arr2[3:]

array([12, 13, 64, 83,  6, 87, 26], dtype=int32)

In [19]:
arr2[2:8]

array([26, 12, 13, 64, 83,  6], dtype=int32)

In [20]:
arr2[6:1:-1]

array([83, 64, 13, 12, 26], dtype=int32)

In [31]:
#arr1[3]
#arr1[2,2]
#arr1[2:4]
arr1[3:]
arr1[3:4]
arr1[2,1:4]
arr1[3,0:4]
arr1[2:4,2]

array([42,  9], dtype=int32)

In [32]:
arr1

array([[27,  3, 33, 24, 23],
       [15, 24, 27, 24, 45],
       [46, 32, 42,  9,  9],
       [31, 19,  9, 22, 12],
       [34, 32, 30, 14, 21]], dtype=int32)

In [33]:
arr1[2:3,3:4]

array([[9]], dtype=int32)

In [34]:
arr1[:4]

array([[27,  3, 33, 24, 23],
       [15, 24, 27, 24, 45],
       [46, 32, 42,  9,  9],
       [31, 19,  9, 22, 12]], dtype=int32)

In [36]:
arr1[:2,4]

array([23, 45], dtype=int32)

In [37]:
arr1[:,:]

array([[27,  3, 33, 24, 23],
       [15, 24, 27, 24, 45],
       [46, 32, 42,  9,  9],
       [31, 19,  9, 22, 12],
       [34, 32, 30, 14, 21]], dtype=int32)

## Condition Selection

In [39]:
arr2

array([60, 14, 26, 12, 13, 64, 83,  6, 87, 26], dtype=int32)

In [40]:
arr2[arr2 % 2 == 0]

array([60, 14, 26, 12, 64,  6, 26], dtype=int32)

In [41]:
arr2[arr2>50]

array([60, 64, 83, 87], dtype=int32)

In [45]:
arr2[(arr2>50) & (arr2 % 2 == 0)]
arr2

array([60, 14, 26, 12, 13, 64, 83,  6, 87, 26], dtype=int32)

In [47]:
arr3 = np.where(arr2 % 2 == 0,2,-1)
arr3

array([ 2,  2,  2,  2, -1,  2, -1,  2, -1,  2])

In [48]:
arr2.sort()

In [49]:
arr2

array([ 6, 12, 13, 14, 26, 26, 60, 64, 83, 87], dtype=int32)

In [50]:
arr1.sort(axis = 0)
arr1

array([[15,  3,  9,  9,  9],
       [27, 19, 27, 14, 12],
       [31, 24, 30, 22, 21],
       [34, 32, 33, 24, 23],
       [46, 32, 42, 24, 45]], dtype=int32)

In [51]:
arr2.sort()

In [52]:
arr2

array([ 6, 12, 13, 14, 26, 26, 60, 64, 83, 87], dtype=int32)

In [53]:
arr2

array([ 6, 12, 13, 14, 26, 26, 60, 64, 83, 87], dtype=int32)

In [54]:
arr2 = np.where(arr2%2 != 0,0,arr2)

In [55]:
arr2

array([ 6, 12,  0, 14, 26, 26, 60, 64,  0,  0], dtype=int32)