In [1]:
import numpy as np

# Creating Array
### 1-D array

In [2]:
arr1 = np.array([1,2,3,4,5,6])

In [3]:
arr1

array([1, 2, 3, 4, 5, 6])

### 2-D array

In [4]:
arr2 = np.array([[11,22,33,44],[10,20,30,40]])

In [5]:
arr2

array([[11, 22, 33, 44],
       [10, 20, 30, 40]])

### 3-D array

In [6]:
arr3 = np.array([[[5,10,15],[10,20,30],[22,33,11]]])

In [7]:
arr3

array([[[ 5, 10, 15],
        [10, 20, 30],
        [22, 33, 11]]])

## 1-D Array (One Dimensional)

Convert the all data in string format.

In [8]:
arr1 = np.array([5,10,"dipak",20])
arr2 = np.array([11,7,22,4])
arr1

array(['5', '10', 'dipak', '20'], dtype='<U21')

In [9]:
arr2

array([11,  7, 22,  4])

In [10]:
a = np.array([7,9,5,6])
b = np.array([8,4,3,3])
a
b

array([8, 4, 3, 3])

In [11]:
sum1 = a + b
sum1

array([15, 13,  8,  9])

In [12]:
mul = a * b
mul

array([56, 36, 15, 18])

In [13]:
div = a // b
div

array([0, 2, 1, 2])

In [14]:
%%time
list1 = [x for x in range(1001,2001)]
list2 = [x for x in range(2002,3002)]
list3 = []
for i in range(len(list1)):
    list3.append(list1[i] + list2[i])

CPU times: total: 0 ns
Wall time: 1.01 ms


In [15]:
%%time
arr1 = np.array([x for x in range(100,200)])
arr2 = np.array([x for x in range(201,301)])
arr3 = arr1 + arr2
arr3


CPU times: total: 0 ns
Wall time: 1.18 ms


array([301, 303, 305, 307, 309, 311, 313, 315, 317, 319, 321, 323, 325,
       327, 329, 331, 333, 335, 337, 339, 341, 343, 345, 347, 349, 351,
       353, 355, 357, 359, 361, 363, 365, 367, 369, 371, 373, 375, 377,
       379, 381, 383, 385, 387, 389, 391, 393, 395, 397, 399, 401, 403,
       405, 407, 409, 411, 413, 415, 417, 419, 421, 423, 425, 427, 429,
       431, 433, 435, 437, 439, 441, 443, 445, 447, 449, 451, 453, 455,
       457, 459, 461, 463, 465, 467, 469, 471, 473, 475, 477, 479, 481,
       483, 485, 487, 489, 491, 493, 495, 497, 499])

In [16]:
import sys

In [17]:
list1 = [1,2,3,4,5,6]
sys.getsizeof(list1[0] * len(list1))

28

In [18]:
arr1 = np.array([1,2,3,4,5,6])
arr1.itemsize * arr1.size

48

## N-D Array (Multi Dimensional)

In [19]:
arr2 = np.array([[34,44,56,78],[67,88,53,25]])
arr2

array([[34, 44, 56, 78],
       [67, 88, 53, 25]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [23]:
arr2 = ([[[3,2,1],[6,5,4],[7,8,9]]])
arr2

[[[3, 2, 1], [6, 5, 4], [7, 8, 9]]]

# Broadcasting

In [24]:
arr1 = np.array([[23,34,43,55],
                 [65,67,87,56]])
arr2 = np.array([42,34,55,12])
arr3 = arr1 + arr2
arr3

array([[ 65,  68,  98,  67],
       [107, 101, 142,  68]])

Operands could not be broadcast together with shapes (6,) (3,) : 

In [25]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([1,2,3])
arr3 = arr1+arr2
arr3

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

In [ ]:
arr2 = np.pad(arr2,(0,3))
arr2
              

In [36]:
A = np.arange(1
              , 10,2)

In [37]:
A

array([1, 3, 5, 7, 9])

In [53]:
# np.random.rand(3)       # 0 to 1
np.random.randint(1, 10,4)

array([2, 7, 5, 8], dtype=int32)

In [79]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [60]:
np.linspace(5,4)

array([5.        , 4.97959184, 4.95918367, 4.93877551, 4.91836735,
       4.89795918, 4.87755102, 4.85714286, 4.83673469, 4.81632653,
       4.79591837, 4.7755102 , 4.75510204, 4.73469388, 4.71428571,
       4.69387755, 4.67346939, 4.65306122, 4.63265306, 4.6122449 ,
       4.59183673, 4.57142857, 4.55102041, 4.53061224, 4.51020408,
       4.48979592, 4.46938776, 4.44897959, 4.42857143, 4.40816327,
       4.3877551 , 4.36734694, 4.34693878, 4.32653061, 4.30612245,
       4.28571429, 4.26530612, 4.24489796, 4.2244898 , 4.20408163,
       4.18367347, 4.16326531, 4.14285714, 4.12244898, 4.10204082,
       4.08163265, 4.06122449, 4.04081633, 4.02040816, 4.        ])

In [61]:
a = np.array([[1], [2], [3]])

In [62]:
a

array([[1],
       [2],
       [3]])

In [63]:
b = np.array([10, 20, 30])

In [64]:
b

array([10, 20, 30])

In [65]:
a+b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [69]:
arr = np.array([1, 2, 3, 4,])
arr.reshape(2, 2)

array([[1, 2],
       [3, 4]])

In [72]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
arr = np.array([10, 25, 30, 15, 40])

In [74]:
arr

array([10, 25, 30, 15, 40])

In [75]:
arr1 = np.where(arr % 2 ==0,2,-1)
arr1

array([ 2, -1,  2, -1,  2])

In [76]:
arr1 = np.where(arr % 2 ==0)
arr1

(array([0, 2, 4]),)

In [81]:
arr.size

5