In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])


In [3]:
arr1


array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.array([1,2,"FBS",4,5])

#

In [5]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([6,7,8,9])

In [6]:
arr3 = arr1 + arr2
arr3

array([ 7,  9, 11, 13])

In [7]:
arr1 = arr1 * 10

In [8]:
arr1

array([10, 20, 30, 40])

In [9]:
arr2 

array([6, 7, 8, 9])

In [10]:
arr2 // 2

array([3, 3, 4, 4])

In [11]:
%%time
list1 = [x for x in range(1,1001)]
list2 = [x for x in range(2001,3001)]
list3 = []
for i in range(len(list1)):
    list3.append(list1[i] + list2[i])

CPU times: total: 0 ns
Wall time: 996 μs


In [12]:
%%time
arr1 = np.array([x for x in range(1,1001)])
arr2 = np.array([x for x in range(2001,3001)])
arr3 = arr1 + arr2
arr3
                

CPU times: total: 0 ns
Wall time: 1.33 ms


array([2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018, 2020, 2022,
       2024, 2026, 2028, 2030, 2032, 2034, 2036, 2038, 2040, 2042, 2044,
       2046, 2048, 2050, 2052, 2054, 2056, 2058, 2060, 2062, 2064, 2066,
       2068, 2070, 2072, 2074, 2076, 2078, 2080, 2082, 2084, 2086, 2088,
       2090, 2092, 2094, 2096, 2098, 2100, 2102, 2104, 2106, 2108, 2110,
       2112, 2114, 2116, 2118, 2120, 2122, 2124, 2126, 2128, 2130, 2132,
       2134, 2136, 2138, 2140, 2142, 2144, 2146, 2148, 2150, 2152, 2154,
       2156, 2158, 2160, 2162, 2164, 2166, 2168, 2170, 2172, 2174, 2176,
       2178, 2180, 2182, 2184, 2186, 2188, 2190, 2192, 2194, 2196, 2198,
       2200, 2202, 2204, 2206, 2208, 2210, 2212, 2214, 2216, 2218, 2220,
       2222, 2224, 2226, 2228, 2230, 2232, 2234, 2236, 2238, 2240, 2242,
       2244, 2246, 2248, 2250, 2252, 2254, 2256, 2258, 2260, 2262, 2264,
       2266, 2268, 2270, 2272, 2274, 2276, 2278, 2280, 2282, 2284, 2286,
       2288, 2290, 2292, 2294, 2296, 2298, 2300, 23

# 

In [13]:
import sys 
list1 = [23,45,69,89]
sys.getsizeof(list1[0] * len(list1))

28

In [14]:
arr1 = np.array([23,45,67,89])
arr1.itemsize * arr1.size

32

In [15]:
arr = np.array([10,20,40,50])
arr

array([10, 20, 40, 50])

In [23]:
newarr = np.insert(arr,2,30)
newarr

array([10, 20, 30, 40, 50])

In [47]:
arr = np.array([[[1,2],
                [3,4],
                [5,6]]])
arr

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [45]:
c= np.append(arr,[[1,2]],axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2]])

In [49]:
new_arr = np.append(arr, [[[7, 8]]], axis=1)
print(new_arr)
# print(new_arr.shape)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
